name: Merge EPG XML

on:
  schedule:
    - cron: '20 11 * * *' #Se ejecuta a las 11:20 AM UTC = 6:20 AM GMT-5
  workflow_dispatch:  # Permite ejecución manual desde la UI de GitHub

jobs:
  merge-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Para push automático

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Versión de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run EPG merge script
      run: python epg-merger.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mxepg.xml
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Actualizado - [$(TZ="America/Cancun" date +"%d-%m-%Y %H:%M GMT-5")] - [$(date +'%d-%m-%Y %H:%M UTC')]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
